artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://github.com/Aina-Siddiqui/DataSets/raw/refs/heads/main/All_Beauty.jsonl.gz'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
data_transformation:
  root_dir: artifacts/data_transformation
  input_data_file: artifacts/data_ingestion/BeautyProducts.jsonl
  tokenizer_filename: 'distilbert/distilbert-base-uncased'
model_trainer :
  root_dir: artifacts/model_training
  data_path: artifacts\data_transformation\transformed_dataset
  model_ckpt: 'distilbert/distilbert-base-uncased'
  